version: 2

updates:
  - package-ecosystem: rust-toolchain
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    schedule:
      interval: monthly
    directories:
      - /
      - /rstm
      - /core
      - /macros
      - /state
      - /traits
